### ISSUE TITLE
Multiple dependencies are missing

### ISSUE THREAD

**Issue by sugatoray** [conda-forge/sentence-transformers-feedstock#22]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Multiple dependencies are missing, when compared to the latest PyPI release (v2.1.0). 
Also, the absence of the dependencies (and them having incorrect version specifications) was causing problems in another conda-forge [PR](https://github.com/conda-forge/staged-recipes/pull/16963).

> **I have pushed a PR #21 to fix this already.** :bulb:

<br/>

**This is what you have now**:

```yaml
requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nltk
    - numpy
    - python >=3.6
    - scikit-learn
    - scipy
    - pytorch >=1.0.1
    - tqdm
    - transformers >=3.1
```

**PyPI `requirements.txt`**:

```
transformers>=4.6.0,<5.0.0
tokenizers>=0.10.3
tqdm
torch>=1.6.0
torchvision
numpy
scikit-learn
scipy
nltk
sentencepiece
huggingface-hub
```
